"""Add education, skills, work experience fields

Revision ID: 1297e3cfb1ac
Revises: f284d312b26b
Create Date: 2024-11-27 02:55:27.841504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1297e3cfb1ac'
down_revision = 'f284d312b26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('work_experience', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('work_experience')
        batch_op.drop_column('skills')
        batch_op.drop_column('education')

    # ### end Alembic commands ###
