"""Added security question and answer fields

Revision ID: 59b4e2396e64
Revises: 5784d39823c3
Create Date: 2024-11-27 03:39:06.907470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b4e2396e64'
down_revision = '5784d39823c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('security_question',
               existing_type=sa.VARCHAR(length=150),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('security_answer',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('security_answer',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('security_question',
               existing_type=sa.VARCHAR(length=150),
               nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###
